"""
Export the trained DL model for on-device (Arduino / MCU) inference.

Two complementary export formats are produced in `../MCU_Deployment/model/`:

1. A pure-C, dependency-free header (`transformer_fault_model.h`) with the
   float32 weights of the tiny MLP baked in as `const float` arrays, plus
   the StandardScaler mean/scale. This mirrors the hand-rolled "TinyAI"
   approach already used in this repo's
   `Edge AI Driver-Behavior & Vehicle-Health Classification` project and
   needs NO extra libraries on the MCU side — just plain C/C++ (works on
   AVR Uno/Nano, ESP32, STM32 Blue Pill, etc.).

2. A quantized int8 TFLite model exported as a C byte array
   (`transformer_fault_model_tflite.h`) for boards that DO have room for
   the TensorFlow Lite for Microcontrollers runtime (e.g. ESP32, STM32
   with enough flash/RAM). This is optional / advanced.

Usage:
    python src/export_to_mcu.py
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import tensorflow as tf

from config import MODELS_DIR, PROJECT_ROOT

MCU_DIR = PROJECT_ROOT.parent / "Transformer_MCU_Deployment"
MCU_MODEL_DIR = MCU_DIR / "model"
MCU_MODEL_DIR.mkdir(parents=True, exist_ok=True)


def array_to_c(name: str, arr: np.ndarray, dtype: str = "float") -> str:
    flat = arr.flatten()
    values = ", ".join(f"{v:.8f}f" if dtype == "float" else str(v) for v in flat)
    shape_comment = "x".join(str(d) for d in arr.shape)
    return (
        f"// shape: {shape_comment}\n"
        f"TFM_PROGMEM const {dtype} {name}[{flat.size}] = {{ {values} }};\n"
    )


def export_plain_c_mlp() -> None:
    model = tf.keras.models.load_model(MODELS_DIR / "dl_model.keras")
    scaler_json = json.loads((MODELS_DIR / "dl_scaler.json").read_text())

    # Expect Dense(16, relu) -> Dense(8, relu) -> Dense(1, sigmoid)
    dense_layers = [layer for layer in model.layers if isinstance(layer, tf.keras.layers.Dense)]
    assert len(dense_layers) == 3, f"expected 3 dense layers, found {len(dense_layers)}"

    w1, b1 = dense_layers[0].get_weights()
    w2, b2 = dense_layers[1].get_weights()
    w3, b3 = dense_layers[2].get_weights()

    n_in, n_h1 = w1.shape
    _, n_h2 = w2.shape
    _, n_out = w3.shape

    mean = np.array(scaler_json["mean"], dtype=np.float32)
    scale = np.array(scaler_json["scale"], dtype=np.float32)
    feature_names = scaler_json["feature_columns"]

    lines = []
    lines.append("// AUTO-GENERATED by src/export_to_mcu.py — do not edit by hand.")
    lines.append("// Tiny MLP for transformer predictive-maintenance fault classification.")
    lines.append(f"// Architecture: Dense({n_in}->{n_h1}, ReLU) -> Dense({n_h1}->{n_h2}, ReLU) -> Dense({n_h2}->{n_out}, Sigmoid)")
    lines.append("#pragma once")
    lines.append("")
    lines.append("// On AVR (Uno/Nano) weight arrays are stored in flash (PROGMEM) since")
    lines.append("// there isn't enough RAM (2 KB) to hold them as normal globals. On")
    lines.append("// 32-bit MCUs (ESP32, STM32, etc.) flash and RAM are already unified")
    lines.append("// address-wise, so PROGMEM/pgm_read_float are simply no-ops there.")
    lines.append("#if defined(__AVR__)")
    lines.append("  #include <avr/pgmspace.h>")
    lines.append("  #define TFM_PROGMEM PROGMEM")
    lines.append("  #define TFM_READ_FLOAT(addr) pgm_read_float(addr)")
    lines.append("  #define TFM_READ_U8(addr) pgm_read_byte(addr)")
    lines.append("#else")
    lines.append("  #define TFM_PROGMEM")
    lines.append("  #define TFM_READ_FLOAT(addr) (*(addr))")
    lines.append("  #define TFM_READ_U8(addr) (*(addr))")
    lines.append("#endif")
    lines.append("")
    lines.append(f"#define TFM_N_INPUTS {n_in}")
    lines.append(f"#define TFM_N_HIDDEN1 {n_h1}")
    lines.append(f"#define TFM_N_HIDDEN2 {n_h2}")
    lines.append(f"#define TFM_N_OUTPUTS {n_out}")
    lines.append("")
    lines.append("// Feature order expected by the model (must match the firmware's")
    lines.append("// sensor-reading / feature-engineering code exactly):")
    lines.append("// " + ", ".join(feature_names))
    lines.append("")
    lines.append(array_to_c("TFM_SCALER_MEAN", mean))
    lines.append(array_to_c("TFM_SCALER_SCALE", scale))
    lines.append(array_to_c("TFM_W1", w1.T))  # store as [out][in] flattened row-major
    lines.append(array_to_c("TFM_B1", b1))
    lines.append(array_to_c("TFM_W2", w2.T))
    lines.append(array_to_c("TFM_B2", b2))
    lines.append(array_to_c("TFM_W3", w3.T))
    lines.append(array_to_c("TFM_B3", b3))

    out_path = MCU_MODEL_DIR / "transformer_fault_model.h"
    out_path.write_text("\n".join(lines))
    print(f"Saved plain-C MLP header -> {out_path} ({out_path.stat().st_size} bytes)")


def export_tflite_c_array() -> None:
    tflite_path = MODELS_DIR / "dl_model_quant.tflite"
    data = tflite_path.read_bytes()

    lines = []
    lines.append("// AUTO-GENERATED by src/export_to_mcu.py — do not edit by hand.")
    lines.append("// int8 quantized TFLite model for use with TensorFlow Lite for")
    lines.append("// Microcontrollers (optional, advanced deployment path).")
    lines.append("#pragma once")
    lines.append("")
    lines.append(f"const unsigned int transformer_fault_model_tflite_len = {len(data)};")
    hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
    lines.append(f"alignas(8) const unsigned char transformer_fault_model_tflite[] = {{ {hex_bytes} }};")

    out_path = MCU_MODEL_DIR / "transformer_fault_model_tflite.h"
    out_path.write_text("\n".join(lines))
    print(f"Saved TFLite C-array header -> {out_path} ({out_path.stat().st_size} bytes, model={len(data)} bytes)")


def main() -> None:
    export_plain_c_mlp()
    export_tflite_c_array()


if __name__ == "__main__":
    main()
