"""
Export a small, deterministic sample of the held-out test set as a C
header (`test_vectors.h`) so the MCU firmware can replay real feature
vectors on-device and compare its own predictions against the
Python/TensorFlow reference — a simple, convincing way to prove that the
quantized/plain-C export matches the model trained on the PC/Colab.

Usage:
    python src/export_test_vectors.py [N_SAMPLES]
"""
from __future__ import annotations

import sys

import json

import numpy as np
import pandas as pd
import tensorflow as tf

from config import DATA_PROCESSED_DIR, MODELS_DIR, PROJECT_ROOT, TARGET_COL

MCU_DIR = PROJECT_ROOT.parent / "Transformer_MCU_Deployment"
MCU_MODEL_DIR = MCU_DIR / "model"
MCU_MODEL_DIR.mkdir(parents=True, exist_ok=True)


def main(n_samples: int = 20) -> None:
    df = pd.read_csv(DATA_PROCESSED_DIR / "test.csv")
    feature_cols = (DATA_PROCESSED_DIR / "feature_columns.txt").read_text().splitlines()

    model = tf.keras.models.load_model(MODELS_DIR / "dl_model.keras")
    scaler_json = json.loads((MODELS_DIR / "dl_scaler.json").read_text())
    mean = np.array(scaler_json["mean"], dtype=np.float32)
    scale = np.array(scaler_json["scale"], dtype=np.float32)

    rng = np.random.RandomState(7)
    idx = rng.choice(len(df), size=min(n_samples, len(df)), replace=False)
    sample = df.iloc[idx].reset_index(drop=True)

    X = sample[feature_cols].values.astype(np.float32)  # RAW features (what the C header stores)
    y_true = sample[TARGET_COL].values.astype(np.int32)
    X_scaled = (X - mean) / scale  # same StandardScaler transform used at train time
    proba = model.predict(X_scaled, verbose=0).ravel()

    n_features = len(feature_cols)
    lines = []
    lines.append("// AUTO-GENERATED by src/export_test_vectors.py — do not edit by hand.")
    lines.append("// A handful of RAW (pre-standardization) feature vectors from the held-out")
    lines.append("// test split, plus the reference Python/TensorFlow prediction for each,")
    lines.append("// so the firmware can self-check its on-device inference against the")
    lines.append("// exact same model trained on PC/Colab.")
    lines.append("#pragma once")
    lines.append("")
    lines.append(f"#define TFM_N_TEST_VECTORS {len(sample)}")
    lines.append("")
    flat = X.flatten()
    values = ", ".join(f"{v:.6f}f" for v in flat)
    lines.append(f"// shape: {len(sample)}x{n_features}")
    lines.append(f"TFM_PROGMEM const float TFM_TEST_X[{flat.size}] = {{ {values} }};")
    lines.append("")
    proba_values = ", ".join(f"{p:.6f}f" for p in proba)
    lines.append(f"TFM_PROGMEM const float TFM_TEST_Y_PROBA[{len(proba)}] = {{ {proba_values} }};")
    lines.append("")
    label_values = ", ".join(str(int(v)) for v in y_true)
    lines.append(f"TFM_PROGMEM const uint8_t TFM_TEST_Y_LABEL[{len(y_true)}] = {{ {label_values} }};")

    out_path = MCU_MODEL_DIR / "test_vectors.h"
    out_path.write_text("\n".join(lines))
    print(f"Saved {len(sample)} test vectors -> {out_path} ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 20
    main(n)
