[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
upload_protocol = serial
#the following lines are for debugging with wokwi
debug_tool = custom
debug_port = localhost:9333
