"""
Emit a slice of the TEST split as a C header the firmware can replay,
together with the host-side expected outputs for a bit-exact comparison.

Why: flashing a model and eyeballing the serial output proves nothing.  With
replay_data.h the firmware chews on the *same* rows the host evaluated, so any
divergence (feature bug, quantisation mismatch, arena corruption) shows up as a
numeric difference rather than a vague "seems fine".

Run:
    python 04_deployment_esp32/scripts/make_replay_data.py --n 240
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from config import ARTIFACT_DIR, DEPLOY_DIR, SPLIT_DIR, WINDOW  # noqa: E402

import tensorflow as tf  # noqa: E402

RAW_COLS = ["VL1", "VL2", "VL3", "IL1", "IL2", "IL3", "OTI", "WTI", "ATI", "OLI"]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=240, help="rows to embed")
    ap.add_argument("--start", type=int, default=None,
                    help="row offset into the processed CSV (default: a busy region)")
    args = ap.parse_args()

    df = pd.read_csv(SPLIT_DIR / "processed_full.csv")
    meta = json.loads((SPLIT_DIR / "meta.json").read_text())
    op = json.loads((ARTIFACT_DIR / "operating_point.json").read_text())

    # default: pick a region containing some degraded samples so the replay is
    # not 240 rows of "everything is fine"
    if args.start is None:
        sev = df["health"].to_numpy()
        n_tr = int(len(df) * 0.70) + int(len(df) * 0.15)   # test region start
        tail = sev[n_tr:]
        win = np.convolve((tail > 0).astype(int), np.ones(args.n, int), "valid")
        args.start = n_tr + int(win.argmax()) if len(win) else n_tr

    sub = df.iloc[args.start: args.start + args.n]
    raw = sub[RAW_COLS].to_numpy(np.float32)
    print(f"[replay] rows {args.start}..{args.start+len(sub)}  "
          f"degraded {(sub['health']>0).sum()}/{len(sub)}")

    # ---- host-side expected outputs -----------------------------------
    nz = np.load(ARTIFACT_DIR / "norm.npz")
    mean, std = nz["mean"], nz["std"]
    r_mean, r_std = float(nz["r_mean"]), float(nz["r_std"])
    feats = sub[meta["features"]].to_numpy(np.float32)

    interp = tf.lite.Interpreter(model_path=str(ARTIFACT_DIR / "model_int8.tflite"))
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    outs = interp.get_output_details()
    o_cls = next(o for o in outs if o["shape"][-1] == 3)
    o_reg = next(o for o in outs if o["shape"][-1] == 1)
    s_in, z_in = inp["quantization"]

    exp = []
    for i in range(WINDOW - 1, len(sub)):
        w = (feats[i - WINDOW + 1: i + 1] - mean) / std
        q = np.clip(np.round(w / s_in) + z_in, -128, 127).astype(np.int8)
        interp.set_tensor(inp["index"], q[None, ...])
        interp.invoke()
        cs, cz = o_cls["quantization"]
        rs, rz = o_reg["quantization"]
        p = (interp.get_tensor(o_cls["index"])[0].astype(np.float32) - cz) * cs
        p = p / max(p.sum(), 1e-6)
        r = (interp.get_tensor(o_reg["index"])[0][0].astype(np.float32) - rz) * rs
        exp.append((i, float(p[1] + p[2]), int(p.argmax()), float(r * r_std + r_mean)))

    # ---- write replay_data.h ------------------------------------------
    hdr = DEPLOY_DIR / "include" / "replay_data.h"
    L = []
    a = L.append
    a("/* AUTO-GENERATED by scripts/make_replay_data.py — do not edit. */")
    a("#ifndef REPLAY_DATA_H")
    a("#define REPLAY_DATA_H")
    a("")
    a(f"#define REPLAY_N {len(raw)}")
    a("/* columns: VL1 VL2 VL3 IL1 IL2 IL3 OTI WTI ATI OLI */")
    a(f"static const float replay_rows[REPLAY_N][10] = {{")
    for row in raw:
        a("  {" + ", ".join(f"{v:.4f}f" for v in row) + "},")
    a("};")
    a("")
    a("/* Host (int8 TFLite) reference outputs, aligned to the row index at")
    a(" * which the firmware should produce them.  Use these to prove the")
    a(" * firmware matches the host bit-for-bit. */")
    a(f"#define REPLAY_EXPECTED_N {len(exp)}")
    a("typedef struct { int row; float risk; int cls; float wti_fc; } replay_exp_t;")
    a("static const replay_exp_t replay_expected[REPLAY_EXPECTED_N] = {")
    for i, risk, cls, wfc in exp:
        a(f"  {{{i}, {risk:.5f}f, {cls}, {wfc:.3f}f}},")
    a("};")
    a("")
    a(f"#define REPLAY_ALARM_THRESH {op['alarm_threshold']:.5f}f")
    a("")
    a("#endif /* REPLAY_DATA_H */")
    hdr.write_text("\n".join(L))
    print(f"[replay] wrote {hdr}  ({hdr.stat().st_size/1024:.1f} KB, "
          f"{len(exp)} expected outputs)")

    # also dump a CSV for the desktop simulator
    out_csv = DEPLOY_DIR / "scripts" / "replay_expected.csv"
    pd.DataFrame(exp, columns=["row", "risk", "cls", "wti_fc"]).to_csv(out_csv, index=False)
    print(f"[replay] wrote {out_csv}")


if __name__ == "__main__":
    main()
